# 匹配模式 0-等同匹配 1-不完全匹配 2-完全匹配
mode: 0

# 正则条件 0-直接匹配 1-需要前缀词 2-需要触发词(默认为图鉴) 3-1||2 4-1&&2
condition: 3

# 指定前缀词，不指定则为#
prefix: '*'

# 指定前缀正则（同上，但是需要转义）
prefixForReg: '(\*|#星铁)'

# 索引撤回时间
recallMsg: 40

# 版本
version: 3

# 触发词,可设置多个
pick:
  - 图鉴